### ISSUE TITLE
Umbrella: Default theme

### ISSUE THREAD

**Issue by kbariotis** [kbariotis/presentador#7]
This is a general ticket to track the initial development of the default theme. It's currently far from perfect and I want to work more on it.

- [ ] responsive layout
- [ ] responsive font sizes
- [ ] readable fonts on bigger screens (its a presentation after all)
- [ ] more states that account for more elements

**Comment by lipis** [comment]
Use the open colors: https://yeun.github.io/open-color/ (It's very subjective of course, but they just look nice)

**Comment by kbariotis** [comment]
I just discovered https://prezibase.com/ and was wondering if we can add some of these transitions to the default theme of Presentador? 

WDYT? https://www.youtube.com/watch?time_continue=3&v=XVl3B1EWhHc&feature=emb_logo

**Comment by lipis** [comment]
Looks great.. I just have no idea how could someone create these presentations.. Every time I see a Prezi presentation I'm speechless.. but it looks hard :)
